id: I0D40D8DD
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T12:40:55+00:00'
last_modified: '2022-06-10T08:38:44.113954+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1PD159529
  title: ཀྲུང་གོའི་བོད་རིག་པ།（རྒྱ་ཡིག་）
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    45E9:
      image_group_id: I4PD4156
      title: Volume 1 of krung go'i bod rig pa/（rgya yig ）
      total_pages: 134
      order: 1
      base_file: 45E9.txt
    D6C3:
      image_group_id: I4PD4157
      title: Volume 2 of krung go'i bod rig pa/（rgya yig ）
      total_pages: 178
      order: 2
      base_file: D6C3.txt
    C341:
      image_group_id: I4PD4158
      title: Volume 3 of krung go'i bod rig pa/（rgya yig ）
      total_pages: 182
      order: 3
      base_file: C341.txt
    023D:
      image_group_id: I4PD4159
      title: Volume 4 of krung go'i bod rig pa/（rgya yig ）
      total_pages: 134
      order: 4
      base_file: 023D.txt
    '8993':
      image_group_id: I4PD4160
      title: Volume 5 of krung go'i bod rig pa/（rgya yig ）
      total_pages: 266
      order: 5
      base_file: 8993.txt
    EC5C:
      image_group_id: I4PD4161
      title: Volume 6 of krung go'i bod rig pa/（rgya yig ）
      total_pages: 150
      order: 6
      base_file: EC5C.txt
    '4613':
      image_group_id: I4PD4162
      title: Volume 7 of krung go'i bod rig pa/（rgya yig ）
      total_pages: 264
      order: 7
      base_file: 4613.txt
    B4ED:
      image_group_id: I4PD4163
      title: Volume 8 of krung go'i bod rig pa/（rgya yig ）
      total_pages: 166
      order: 8
      base_file: B4ED.txt
    F5DB:
      image_group_id: I4PD4164
      title: Volume 9 of krung go'i bod rig pa/（rgya yig ）
      total_pages: 264
      order: 9
      base_file: F5DB.txt
    E594:
      image_group_id: I4PD4165
      title: Volume 10 of krung go'i bod rig pa/（rgya yig ）
      total_pages: 150
      order: 10
      base_file: E594.txt
    B240:
      image_group_id: I4PD4166
      title: Volume 11 of krung go'i bod rig pa/（rgya yig ）
      total_pages: 264
      order: 11
      base_file: B240.txt
    8F2B:
      image_group_id: I4PD4167
      title: Volume 12 of krung go'i bod rig pa/（rgya yig ）
      total_pages: 150
      order: 12
      base_file: 8F2B.txt
    BEAB:
      image_group_id: I4PD4168
      title: Volume 13 of krung go'i bod rig pa/（rgya yig ）
      total_pages: 150
      order: 13
      base_file: BEAB.txt
    538A:
      image_group_id: I4PD4169
      title: Volume 14 of krung go'i bod rig pa/（rgya yig ）
      total_pages: 150
      order: 14
      base_file: 538A.txt
    47D4:
      image_group_id: I4PD4170
      title: Volume 15 of krung go'i bod rig pa/（rgya yig ）
      total_pages: 238
      order: 15
      base_file: 47D4.txt
    2AAA:
      image_group_id: I4PD4171
      title: Volume 16 of krung go'i bod rig pa/（rgya yig ）
      total_pages: 182
      order: 16
      base_file: 2AAA.txt
    B88B:
      image_group_id: I4PD4172
      title: Volume 17 of krung go'i bod rig pa/（rgya yig ）
      total_pages: 198
      order: 17
      base_file: B88B.txt
    C77C:
      image_group_id: I4PD4173
      title: Volume 18 of krung go'i bod rig pa/（rgya yig ）
      total_pages: 266
      order: 18
      base_file: C77C.txt
    78F1:
      image_group_id: I4PD4174
      title: Volume 19 of krung go'i bod rig pa/（rgya yig ）
      total_pages: 194
      order: 19
      base_file: 78F1.txt
    A74D:
      image_group_id: I4PD4175
      title: Volume 20 of krung go'i bod rig pa/（rgya yig ）
      total_pages: 166
      order: 20
      base_file: A74D.txt
    E113:
      image_group_id: I4PD4176
      title: Volume 21 of krung go'i bod rig pa/（rgya yig ）
      total_pages: 208
      order: 21
      base_file: E113.txt
    333A:
      image_group_id: I4PD4177
      title: Volume 22 of krung go'i bod rig pa/（rgya yig ）
      total_pages: 264
      order: 22
      base_file: 333A.txt
    282C:
      image_group_id: I4PD4178
      title: Volume 23 of krung go'i bod rig pa/（rgya yig ）
      total_pages: 226
      order: 23
      base_file: 282C.txt
    8CAC:
      image_group_id: I4PD4179
      title: Volume 24 of krung go'i bod rig pa/（rgya yig ）
      total_pages: 206
      order: 24
      base_file: 8CAC.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
